### ISSUE TITLE
Cannot Install, first missing llama Index, then  cannot import name 'SimpleDirectoryReader' from 'llama_index' (unknown location)

### ISSUE THREAD

**Issue by Daeliel** [4dh/GRDN#10]
2024-05-12 14:01:01.306 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\GRDN_env\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "F:\GRDN\app.py", line 15, in <module>
    from src.backend.chatbot import *
  File "F:\GRDN\src\backend\chatbot.py", line 11, in <module>
    from llama_index import (
ModuleNotFoundError: No module named 'llama_index'

After this, I tried installing llama_index, and the next error is:

ImportError: cannot import name 'SimpleDirectoryReader' from 'llama_index' (unknown location)
2024-05-12 14:05:45.404 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\GRDN_env\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "F:\GRDN\app.py", line 15, in <module>
    from src.backend.chatbot import *
  File "F:\GRDN\src\backend\chatbot.py", line 11, in <module>
    from llama_index import (
ImportError: cannot import name 'SimpleDirectoryReader' from 'llama_index' (unknown location)

I've installed this following your instructions: I'm on Pyhton 3.9, Conda, Windows 10.

**Comment by Daeliel** [comment]
Solution: it was deprecated: 

Use: from llama_index.core import 
Also, should llama_index be a part of requirements.txt? 

Finally it might be useful to newbie users to have python version be spelled out somewhere.
Looking forward to trying your app. If I run into any more issues, I'll post!
